### ISSUE TITLE
remove build dir from plugin

### ISSUE THREAD

**Issue by solverat** [dpfaffenbauer/pimcore-coreshop#48]
the `build` dir causes double content and a wrong index in most of IDE.

**Comment by dpfaffenbauer** [comment]
you can exclude the build directory in your IDE.

currently, i don't have any other solution. one thing is: we could zip the builds into those directories. this would decrease the filesize and there would not be any PHP files in there. Since zip/zlib is already a requirement, this is my only current solution (without hosting anything like update.coreshop.org)

**Comment by solverat** [comment]
https://github.com/pimcore/pimcore/issues/406

**Comment by solverat** [comment]
fixed in 61ecba588da17f971aacc15e8fd582fdd12016df
